import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { LogoutButton } from "./_components/logout-button";
import { COOKIE_NAME, verifyToken } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function isAuthenticated(): Promise<boolean> {
  const secret = process.env.AUTH_SECRET;
  const cookieValue = (await cookies()).get(COOKIE_NAME)?.value;
  if (!secret || !cookieValue) return false;
  return verifyToken(secret, cookieValue);
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authed = await isAuthenticated();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {authed && (
          <header className="flex justify-end px-4 py-2 border-b">
            <LogoutButton />
          </header>
        )}
        {children}
      </body>
    </html>
  );
}
